version: "3.8"

services:
  alice:
    build:
      context: ./alice
      args:
        USERNAME: alice
    container_name: alice-mail
    hostname: alice.local
    networks:
      mailnet:
        ipv4_address: 172.28.0.2

  bob:
    build:
      context: ./bob
      args:
        USERNAME: bob
    container_name: bob-mail
    hostname: bob.local
    networks:
      mailnet:
        ipv4_address: 172.28.0.3

networks:
  mailnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
