version: '3.8'

services:
  alice-mail:
    build:
      context: ./alice
    container_name: alice-mail
    hostname: alice.local
    networks:
      mailnet:
        ipv4_address: 172.28.0.2
    cap_add:
      - NET_ADMIN
    tty: true

  bob-mail:
    build:
      context: ./bob
    container_name: bob-mail
    hostname: bob.local
    networks:
      mailnet:
        ipv4_address: 172.28.0.3
    cap_add:
      - NET_ADMIN
    tty: true

networks:
  mailnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
